### ISSUE TITLE
Array with no items key casues error (OpenAPI 3.1)

### ISSUE THREAD

**Issue by mands** [orval-labs/orval#1433]
## What are the steps to reproduce this issue?

1. Using the following minimal OpenAPI 3.1 spec, API generation fails

```json
{
    "info": {
        "title": "app",
        "version": "0.3.1"
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "/"
        }
    ],
    "paths": {
        "/api/auth/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Login with Firebase",
                "operationId": "FBLogin",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UserFBAuthSchema"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "204": {
                        "description": "Request fulfilled, nothing follows",
                        "headers": {}
                    },
                    "400": {
                        "description": "Bad request syntax or unsupported method",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "status_code": {
                                            "type": "integer"
                                        },
                                        "detail": {
                                            "type": "string"
                                        },
                                        "extra": {
                                            "additionalProperties": {},
                                            "type": [
                                                "null",
                                                "object",
                                                "array"
                                            ]
                                        }
                                    },
                                    "type": "object",
                                    "required": [
                                        "detail",
                                        "status_code"
                                    ],
                                    "description": "Validation Exception",
                                    "examples": [
                                        {
                                            "status_code": 400,
                                            "detail": "Bad Request",
                                            "extra": {}
                                        }
                                    ]
                                }
                            }
                        }
                    }
                },
                "deprecated": false,
                "security": [
                    {}
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "UserFBAuthSchema": {
                "properties": {
                    "id_token": {
                        "type": "string"
                    }
                },
                "type": "object",
                "required": [
                    "id_token"
                ],
                "title": "UserFBAuthSchema"
            }
        },
        "securitySchemes": {
            "sessionCookie": {
                "type": "apiKey",
                "description": "Session cookie authentication.",
                "name": "__session",
                "in": "cookie"
            }
        }
    },
    "security": [
        {
            "sessionCookie": []
        }
    ]
}

```

## What happens?

API generation fails with a stacktrace, as per below

## What were you expecting to happen?

The API is generated

## Any logs, error output, etc?

```
$ npx orval --config ./orval.config.ts
🍻 Start orval v6.29.1 - A swagger client generator for typescript
🛑 test - Error: All arrays must have an `items` key defined (name=FBLogin400ExtraAnyOfTwo, schema={"additionalProperties":{},"type":"array"})
    at getArray (/Users/m/dev/test/spa/node_modules/@orval/core/dist/index.js:41395:11)
    at getScalar (/Users/m/dev/test/spa/node_modules/@orval/core/dist/index.js:41950:34)
    at resolveValue (/Users/m/dev/test/spa/node_modules/@orval/core/dist/index.js:41245:18)
    at resolveObjectOriginal (/Users/m/dev/test/spa/node_modules/@orval/core/dist/index.js:41260:25)
    at resolveObject (/Users/m/dev/test/spa/node_modules/@orval/core/dist/index.js:41329:18)
    at items.reduce.values (/Users/m/dev/test/spa/node_modules/@orval/core/dist/index.js:42082:30)
    at Array.reduce (<anonymous>)
    at combineSchemas (/Users/m/dev/test/spa/node_modules/@orval/core/dist/index.js:42076:30)
    at getObject (/Users/m/dev/test/spa/node_modules/@orval/core/dist/index.js:41769:12)
    at getScalar (/Users/m/dev/test/spa/node_modules/@orval/core/dist/index.js:42017:34)
```

## Any other comments?

I understand this may have been an issue with OpenAPI 3.0, as the `items` field was required for an `array`, but is no longer the case for 3.1, where the `items` field is not longer required.

## What versions are you using?

- `orval/6.29.1 darwin-arm64 node-v20.14.0`

**Comment by DragosRomaniuc** [comment]
up
